version: "3.3"
services:
  postgres:
    container_name: db
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: bot
    shm_size: 400mb
    command: postgres -c shared_buffers=400MB -c work_mem=10MB
    env_file: local.env

  app:
    container_name: vtbot_app
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    env_file: local.env
    depends_on:
      - postgres
    # volumes:
    #   - /path-to-bot/uploads:/app/uploads
