version: "3.3"
services:
  postgres:
    container_name: db
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: bot
    build:
      context: .
      dockerfile: DockerfilePostgres
    ports:
      - "5447:5432"
    command: postgres -c shared_buffers=400MB -c work_mem=10MB
    env_file: local.env

  app:
    # ports:
    #   - "443:5000"
    environment:
      - NODE_ENV=production
    #   - HOST=0.0.0.0
    #   - PORT=5000
    restart: always
    env_file: local.env
    depends_on:
      - postgres
